### ISSUE TITLE
Adding the last bug fix commit to CPAN

### ISSUE THREAD

**Issue by h4iku** [kiamazi/MarkMoreDown#2]
Hi,
I think the latest bug fix commit a5c5f0626df7ad70b4fa5a8db2d07d5090e0078e is not on CPAN, causing Mira to error out on build:

```
Undefined subroutine &Text::Markmoredown::Header2Label called at C:/Strawberry/perl/site/lib/Text/Markmoredown.pm line 1825.
```

Installing the repository version fixes the issue.

**Comment by kiamazi** [comment]
:(
wow, such a big mistakes

**Comment by h4iku** [comment]
Fixed now, thank you.
